id: 09_aws_taxi_scheduled
namespace: zoomcamp
description: |
  Best to add a label `backfill:true` from the UI to track executions created via a backfill.
  CSV data used here comes from: https://github.com/DataTalksClub/nyc-tlc-data/releases
  Adapted to use AWS S3 + Athena (Iceberg) instead of GCP GCS + BigQuery.

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: green

variables:
  file: "{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}.csv"
  s3_key: "staging/{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}/{{vars.file}}"
  s3_staging_uri: "s3://{{kv('S3_BUCKET_NAME')}}/staging/{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}/"
  table: "{{kv('AWS_DATASET')}}.{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy_MM')}}"
  data: "{{outputs.extract.outputFiles[inputs.taxi ~ '_tripdata_' ~ (trigger.date | date('yyyy-MM')) ~ '.csv']}}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{render(vars.file)}}.gz | gunzip > {{render(vars.file)}}
      - echo "Q1 - Uncompressed file size:" && ls -lh {{render(vars.file)}}

  - id: upload_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from: "{{render(vars.data)}}"
    key: "{{render(vars.s3_key)}}"
    bucket: "{{kv('S3_BUCKET_NAME')}}"

  - id: if_yellow_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'yellow'}}"
    then:
      - id: athena_yellow_tripdata
        type: io.kestra.plugin.aws.athena.Query
        query: |
          CREATE TABLE IF NOT EXISTS {{kv('AWS_DATASET')}}.yellow_tripdata (
              unique_row_id binary,
              filename string,
              VendorID string,
              tpep_pickup_datetime timestamp,
              tpep_dropoff_datetime timestamp,
              passenger_count bigint,
              trip_distance double,
              RatecodeID string,
              store_and_fwd_flag string,
              PULocationID string,
              DOLocationID string,
              payment_type bigint,
              fare_amount double,
              extra double,
              mta_tax double,
              tip_amount double,
              tolls_amount double,
              improvement_surcharge double,
              total_amount double,
              congestion_surcharge double
          )
          PARTITIONED BY (day(tpep_pickup_datetime))
          LOCATION 's3://{{kv('S3_BUCKET_NAME')}}/warehouse/yellow_tripdata/'
          TBLPROPERTIES ('table_type' = 'ICEBERG')

      - id: athena_yellow_drop_ext
        type: io.kestra.plugin.aws.athena.Query
        query: |
          DROP TABLE IF EXISTS {{render(vars.table)}}_ext

      - id: athena_yellow_create_ext
        type: io.kestra.plugin.aws.athena.Query
        query: |
          CREATE EXTERNAL TABLE {{render(vars.table)}}_ext (
              VendorID string,
              tpep_pickup_datetime string,
              tpep_dropoff_datetime string,
              passenger_count string,
              trip_distance string,
              RatecodeID string,
              store_and_fwd_flag string,
              PULocationID string,
              DOLocationID string,
              payment_type string,
              fare_amount string,
              extra string,
              mta_tax string,
              tip_amount string,
              tolls_amount string,
              improvement_surcharge string,
              total_amount string,
              congestion_surcharge string
          )
          ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          WITH SERDEPROPERTIES (
              'separatorChar' = ',',
              'quoteChar' = '"'
          )
          STORED AS TEXTFILE
          LOCATION '{{render(vars.s3_staging_uri)}}'
          TBLPROPERTIES ('skip.header.line.count' = '1')

      - id: athena_yellow_merge
        type: io.kestra.plugin.aws.athena.Query
        query: |
          MERGE INTO {{kv('AWS_DATASET')}}.yellow_tripdata T
          USING (
              SELECT
                  md5(to_utf8(CONCAT(
                      COALESCE(VendorID, ''),
                      COALESCE(tpep_pickup_datetime, ''),
                      COALESCE(tpep_dropoff_datetime, ''),
                      COALESCE(PULocationID, ''),
                      COALESCE(DOLocationID, '')
                  ))) AS unique_row_id,
                  '{{render(vars.file)}}' AS filename,
                  VendorID,
                  CAST(tpep_pickup_datetime AS timestamp) AS tpep_pickup_datetime,
                  CAST(tpep_dropoff_datetime AS timestamp) AS tpep_dropoff_datetime,
                  TRY_CAST(passenger_count AS bigint) AS passenger_count,
                  TRY_CAST(trip_distance AS double) AS trip_distance,
                  RatecodeID,
                  store_and_fwd_flag,
                  PULocationID,
                  DOLocationID,
                  TRY_CAST(payment_type AS bigint) AS payment_type,
                  TRY_CAST(fare_amount AS double) AS fare_amount,
                  TRY_CAST(extra AS double) AS extra,
                  TRY_CAST(mta_tax AS double) AS mta_tax,
                  TRY_CAST(tip_amount AS double) AS tip_amount,
                  TRY_CAST(tolls_amount AS double) AS tolls_amount,
                  TRY_CAST(improvement_surcharge AS double) AS improvement_surcharge,
                  TRY_CAST(total_amount AS double) AS total_amount,
                  TRY_CAST(congestion_surcharge AS double) AS congestion_surcharge
              FROM {{render(vars.table)}}_ext
          ) S
          ON T.unique_row_id = S.unique_row_id
          WHEN NOT MATCHED THEN
              INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge)
              VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance, S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge)

      - id: athena_yellow_file_count
        type: io.kestra.plugin.aws.athena.Query
        query: |
          SELECT COUNT(*) AS row_count
          FROM {{kv('AWS_DATASET')}}.yellow_tripdata
          WHERE filename = '{{render(vars.file)}}'

  - id: if_green_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'green'}}"
    then:
      - id: athena_green_tripdata
        type: io.kestra.plugin.aws.athena.Query
        query: |
          CREATE TABLE IF NOT EXISTS {{kv('AWS_DATASET')}}.green_tripdata (
              unique_row_id binary,
              filename string,
              VendorID string,
              lpep_pickup_datetime timestamp,
              lpep_dropoff_datetime timestamp,
              store_and_fwd_flag string,
              RatecodeID string,
              PULocationID string,
              DOLocationID string,
              passenger_count bigint,
              trip_distance double,
              fare_amount double,
              extra double,
              mta_tax double,
              tip_amount double,
              tolls_amount double,
              ehail_fee double,
              improvement_surcharge double,
              total_amount double,
              payment_type bigint,
              trip_type string,
              congestion_surcharge double
          )
          PARTITIONED BY (day(lpep_pickup_datetime))
          LOCATION 's3://{{kv('S3_BUCKET_NAME')}}/warehouse/green_tripdata/'
          TBLPROPERTIES ('table_type' = 'ICEBERG')

      - id: athena_green_drop_ext
        type: io.kestra.plugin.aws.athena.Query
        query: |
          DROP TABLE IF EXISTS {{render(vars.table)}}_ext

      - id: athena_green_create_ext
        type: io.kestra.plugin.aws.athena.Query
        query: |
          CREATE EXTERNAL TABLE {{render(vars.table)}}_ext (
              VendorID string,
              lpep_pickup_datetime string,
              lpep_dropoff_datetime string,
              store_and_fwd_flag string,
              RatecodeID string,
              PULocationID string,
              DOLocationID string,
              passenger_count string,
              trip_distance string,
              fare_amount string,
              extra string,
              mta_tax string,
              tip_amount string,
              tolls_amount string,
              ehail_fee string,
              improvement_surcharge string,
              total_amount string,
              payment_type string,
              trip_type string,
              congestion_surcharge string
          )
          ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          WITH SERDEPROPERTIES (
              'separatorChar' = ',',
              'quoteChar' = '"'
          )
          STORED AS TEXTFILE
          LOCATION '{{render(vars.s3_staging_uri)}}'
          TBLPROPERTIES ('skip.header.line.count' = '1')

      - id: athena_green_merge
        type: io.kestra.plugin.aws.athena.Query
        query: |
          MERGE INTO {{kv('AWS_DATASET')}}.green_tripdata T
          USING (
              SELECT
                  md5(to_utf8(CONCAT(
                      COALESCE(VendorID, ''),
                      COALESCE(lpep_pickup_datetime, ''),
                      COALESCE(lpep_dropoff_datetime, ''),
                      COALESCE(PULocationID, ''),
                      COALESCE(DOLocationID, '')
                  ))) AS unique_row_id,
                  '{{render(vars.file)}}' AS filename,
                  VendorID,
                  CAST(lpep_pickup_datetime AS timestamp) AS lpep_pickup_datetime,
                  CAST(lpep_dropoff_datetime AS timestamp) AS lpep_dropoff_datetime,
                  store_and_fwd_flag,
                  RatecodeID,
                  PULocationID,
                  DOLocationID,
                  TRY_CAST(passenger_count AS bigint) AS passenger_count,
                  TRY_CAST(trip_distance AS double) AS trip_distance,
                  TRY_CAST(fare_amount AS double) AS fare_amount,
                  TRY_CAST(extra AS double) AS extra,
                  TRY_CAST(mta_tax AS double) AS mta_tax,
                  TRY_CAST(tip_amount AS double) AS tip_amount,
                  TRY_CAST(tolls_amount AS double) AS tolls_amount,
                  TRY_CAST(ehail_fee AS double) AS ehail_fee,
                  TRY_CAST(improvement_surcharge AS double) AS improvement_surcharge,
                  TRY_CAST(total_amount AS double) AS total_amount,
                  TRY_CAST(payment_type AS bigint) AS payment_type,
                  trip_type,
                  TRY_CAST(congestion_surcharge AS double) AS congestion_surcharge
              FROM {{render(vars.table)}}_ext
          ) S
          ON T.unique_row_id = S.unique_row_id
          WHEN NOT MATCHED THEN
              INSERT (unique_row_id, filename, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)
              VALUES (S.unique_row_id, S.filename, S.VendorID, S.lpep_pickup_datetime, S.lpep_dropoff_datetime, S.store_and_fwd_flag, S.RatecodeID, S.PULocationID, S.DOLocationID, S.passenger_count, S.trip_distance, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.ehail_fee, S.improvement_surcharge, S.total_amount, S.payment_type, S.trip_type, S.congestion_surcharge)

      - id: athena_green_file_count
        type: io.kestra.plugin.aws.athena.Query
        query: |
          SELECT COUNT(*) AS row_count
          FROM {{kv('AWS_DATASET')}}.green_tripdata
          WHERE filename = '{{render(vars.file)}}'

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.aws
    values:
      accessKeyId: "{{kv('AWS_ACCESS_KEY_ID')}}"
      secretKeyId: "{{kv('AWS_SECRET_ACCESS_KEY')}}"
      region: "{{kv('AWS_REGION')}}"
  - type: io.kestra.plugin.aws.athena.Query
    values:
      database: "{{kv('AWS_DATASET')}}"
      outputLocation: "{{kv('ATHENA_OUTPUT_LOCATION')}}"

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 1 * *"
    inputs:
      taxi: yellow
